### ISSUE TITLE
【意見募集】プラグイン機能

### ISSUE THREAD

**Issue by ci7lus** [ci7lus/MirakTest#12]
現状組み込みになっているコメントレンダラなどを外部jsに切り出せるようにする

サンプルプラグイン実装: https://github.com/ci7lus/miraktest-plugins

- [x] #13
- [x] 呼び出し仕様決定
- [x] コメントレンダラを切り出す
- [x] #44

**Comment by ci7lus** [comment]
https://github.com/ci7lus/MirakTest/commits/feat/v2 にて作業を進めていまーす

基本実装; 84fb2c1eb69af9cea1392dc8cc1b43868ea8673a

**Comment by ci7lus** [comment]
https://github.com/ci7lus/MirakTest/releases/tag/v2.0.0-beta.0

**Comment by kilinbox** [comment]
お疲れ様です。毎日のようにMirakTestを利用させていただいております。
Macで利用しています。
dplayerやzenzaの機能になってくるのかもしれませんが、
sayaのコメントの大きさを変えることができたらいいなと思いました。
理由は4Kディスプレイに全画面表示させたときにコメントが小さく感じるからです。
今はメニューの「表示」→「Zoom In」 / 「Zoom Out」を使って大きさ調整していますが、
コメント以外のインターフェース全般まで大きさが変わります。
コメントだけの大きさを変える方法もあってもいいのではと思いました。

**Comment by ci7lus** [comment]
@kilinbox コメントありがとうございます！
なるほど、FHDで出すとコメントちょっと小さめになるなーとは思ってましたが、4Kディスプレイで出すとかなり小さくなりそうですね…。
とりあえず現状動く DPlayer 側で拡大率のような機能を実装してみようと思います。

**Comment by ci7lus** [comment]
というかそういうプラグインレベルの対策も必要ですが、実は番組表示とかも表示サイズでかくなると豆粒になってそう、アプリレベルの対策も考えます

**Comment by kilinbox** [comment]
連投失礼します。
私の設定及び環境に誤りがあるのかもしれませんが、EPGStation連携プラグインが動作しませんでした。
EPGStationで録画している番組一覧は表示されるのですが、視聴ボタンを押しても動画が再生されません。
使用したEPGStationプラグインは2021100512のものです。

MirakTestはMac版v2.0.0-beta.0
試したEPGStationは以下の2つ。どちらも動作しませんでした。
Windows上で動作させている2.6.11、Raspberry Piで動かしている2.2.1。以上となります。
<img width="1697" alt="Screen Shot 2021-10-06 at 1 21 04" src="https://user-images.githubusercontent.com/17141779/136064193-48ddd756-db84-4feb-8d8d-64fdeb8e6335.png">

**Comment by ci7lus** [comment]
@kilinbox 認証等ない環境だとすんなりつながるはずなんですが、番組情報取れてて映像流れないのはちょっと奇妙ですね。プラグインのリポの方に起票しますので、そちらに「表示->Toggle Developer Tool->Console->中央上Default levels->Verboseにチェックを入れる」を行ってVLCのログを出した状態で、接続に失敗してそうな部分のスクリーンショット or ログを、重要な情報（パスワードはパスなど）を隠した状態で貼ってもらってもよろしいでしょうか。

![image](https://user-images.githubusercontent.com/7887955/136065897-5fefd41f-c5ab-4212-943c-5149105f4848.png)

**Comment by kilinbox** [comment]
お忙しいと思いますが、web-bmlを使用したデータ放送プラグインがあったら嬉しいなって思いました
