### ISSUE TITLE
v2.0.0-beta.2 で再生できなくなる

### ISSUE THREAD

**Issue by xqq** [ci7lus/MirakTest#30]
OS: macOS Monterey 12.0.1 aarch64 (Rosetta 2)
Mirakurun: v3.5.0

現象：いかなるサービスでも「映像の受信に失敗しました」となる

Mirakurun logs: 
```bash
0|mirakurun-server  | 2021-12-11T17:17:06.077+09:00 info: 192.168.1.199 - GET /api/services/3273601024/stream HTTP/1.1 403 - - 3.187 ms VLC/3.0.16 LibVLC/3.0.16 vlc-miraktest (+https://github.com/vivid-lapin/vlc-miraktest)
0|mirakurun-server  | 2021-12-11T17:17:06.086+09:00 info: 192.168.1.199 - GET /api/services/3273601024/stream HTTP/1.0 403 - - 0.411 ms VLC/3.0.16 LibVLC/3.0.16 vlc-miraktest (+https://github.com/vivid-lapin/vlc-miraktest)
```

なお、EPGStation を用いる再生は異常なし。

**Comment by kilinbox** [comment]
私の環境でも再生できませんでした。
2.0.0-beta.1までは問題ありませんでした。

OS: macOS Monterey 12.0.1
Mac mini (M1, 2020)
Mirakurun: 3.9.0-beta.21

![miraktest_error](https://user-images.githubusercontent.com/17141779/145670888-7ec289d5-b39e-4a41-ac82-57c74f001e9e.jpg)

**Comment by ci7lus** [comment]
報告ありがとうございます！ちょっと調査してみます。

**Comment by ci7lus** [comment]
@xqq @kilinbox 
https://github.com/Chinachu/Mirakurun/blob/28b40fa7906c81cacc798281f6132b0a2ab08818/src/Mirakurun/Server.ts#L121 の通りリファラがついてると403で蹴るっぽくて、自分の環境だとnginxか何かで外れてて気づきませんでした。
https://github.com/ci7lus/MirakTest/actions/runs/1566704121 のArtifactsからダウンロードして動くかどうか試してもらってもいいでしょうか。

**Comment by kilinbox** [comment]
@ci7lus 
> https://github.com/ci7lus/MirakTest/actions/runs/1566704121 

ありがとうございます。こちらは問題なく再生できました。

**Comment by ci7lus** [comment]
beta.2のバイナリを不具合を修正した 6fd1380 以降に差し替えました、報告ありがとうございました！

**Comment by xqq** [comment]
報告遅れてすみません。
こちらも問題なく再生できました。

修正ありがとうございます。
