### ISSUE TITLE
macOS HiDPI でメニューが大きすぎる

### ISSUE THREAD

**Issue by xqq** [ci7lus/MirakTest#31]
MirakTest を開発してくれて、いつもありがとうございます。

HiDPI の macOS 環境において、個人的にはメニューがデカすぎるではないかと思います。

もしこれは意図的であれば、この issue を close しても良いと思います。

<img width="1833" alt="image" src="https://user-images.githubusercontent.com/4645762/145676977-36175dd2-2d07-4773-aabc-a9775b07a0af.png">

**Comment by ci7lus** [comment]
このアプリは全体的にウィンドウサイズからの相対サイズ（rem）で指定するようにしていて、理由としては https://github.com/ci7lus/MirakTest/issues/12#issuecomment-934551154 とそれを受けて立てた https://github.com/ci7lus/MirakTest/issues/17 が詳しいのですが、4K画面など大きな画面で表示するとUIが小さく出そうなので、操作できないぐらいなら大きい方がいいだろうと思いこうしています。

私は大きい画面を持っていないのでMacBookPro 13inの全画面程度でしか確認できないのですが、実際大きな画面だと今の指定はどういう感じになっているんでしょうか。現状で大体うまく使えている、もう少し小さくてもいい、何px以下ぐらいの方がいいなどあれば教えていただけるとうれしいです cc: @kilinbox 

また次のリリースまでにはselectでのサービス選択もサイドメニューに移行するつもりでいて、そのメニューは無くなるんですが、サイズ感の問題はrem指定の限りは関係すると思うので検討の余地ありです。

デザインまだまだですが大体のイメージ画面:
![image](https://user-images.githubusercontent.com/7887955/145678134-70d64a38-b247-4ea2-a785-79e96d97c47d.png)

**Comment by xqq** [comment]
27 インチの 4k モニタ使っているのですが、ロジカル解像度は 2560x1440 となっています。

もしテレビの場合などであれば、UI 要素のサイズは viewport のサイズにそのまま連動してもいいですが、

パソコンのユーザーとしては、やっぱりそのまま連動すると UI 要素は大きすぎるかなと思います。

<img width="2560" alt="image" src="https://user-images.githubusercontent.com/4645762/145678639-88ebefc8-8e0a-412f-86fc-2b809886946d.png">

ちなみに、右クリックのメニューはこんな感じです。

<img width="1023" alt="image" src="https://user-images.githubusercontent.com/4645762/145678708-65f5b35b-6112-4b33-a808-89ca3a012a01.png">

**Comment by ci7lus** [comment]
なるほど、4Kモニタで大きすぎる感じだと調整の余地充分にありかもしれません。
今試してみたら `max(14px, 1.5vw)` でなくて `max(14px, 1.2vw)` 程度でちょうどな気がしてきました。

![貼り付けた画像_2021_12_11_22_56](https://user-images.githubusercontent.com/7887955/145679246-1773ca2a-7270-4006-9b34-c45e796cf8c5.jpg)

試しにビルドしてみたので以下から試してみてください:
https://github.com/ci7lus/MirakTest/actions/runs/1567190697

**Comment by xqq** [comment]
小さくなってきましたね。

おおむね納得になっていると思いますが、ただ、

UI 要素のサイズがウィンドサイズに連動して動的変化する一方、右クリックのメニューは OS の UI に一致するため、
右クリックメニューのサイズが他の要素と大きく違って違和感が生じています。

個人的には OS の UI 要素のサイズ（DPI のみに依存）に一致するほうがパソコン的な UI だと思いますが...

<img width="2560" alt="image" src="https://user-images.githubusercontent.com/4645762/145680155-f41f6d6e-c989-422b-8e41-86f322bc4a4a.png">

**Comment by ci7lus** [comment]
とりあえず最大サイズが100%を超えないようにしてみました。ただ無指定にするとウィンドウをが小さめのときに大きすぎるのですが、`clamp(14px, 1.25vw, 100%)` あたりでうまく調整できている気がします。
https://github.com/ci7lus/MirakTest/actions/runs/1567361078

**Comment by kilinbox** [comment]
ccいただいたので私からもご報告。
私は43インチの4K解像度ディスプレイをスケール変えて利用しています。
画面が物理的に大きいので少し離れて見ている感じですね。

> Resolution: 3840 x 2160 (2160p/4K UHD 1 - Ultra High Definition)
> UI Looks like: 1920 x 1080 @ 60.00Hz

結論を申しますと、修正前も修正後も特に問題ありません。

![MirakTest-2 0 0-beta 2](https://user-images.githubusercontent.com/17141779/145696573-eefe72f8-c625-4875-b34d-3069a155d8b0.jpg)

![MirakTest-2 0 0-nightly-1567361078](https://user-images.githubusercontent.com/17141779/145696580-cf16c7d6-00f2-4662-a8fa-85361c053bc7.jpg)

**Comment by xqq** [comment]
> とりあえず最大サイズが100%を超えないようにしてみました。ただ無指定にするとウィンドウをが小さめのときに大きすぎるのですが、`clamp(14px, 1.25vw, 100%)` あたりでうまく調整できている気がします。 https://github.com/ci7lus/MirakTest/actions/runs/1567361078

とても良くなりました。ありがとうございます。

**Comment by ci7lus** [comment]
お二方とも確認ありがとうございます、大丈夫そうなので次回リリースに含めたいと思います。
