### ISSUE TITLE
mirakcのapi/statusとの互換性をもたせる

### ISSUE THREAD

**Issue by ci7lus** [ci7lus/MirakTest#52]
> @humiaozuzu:
> @ci7lus Currently Mirakc do not implement `/api/status` API (will return an empty object) and this change will break Mirakc support For Mirakc api docs: https://github.com/mirakc/mirakc/blob/main/docs/web-api.md#apistatus
> https://github.com/ci7lus/MirakTest/commit/f2139cf0d7a03c9a5aea9a794d6d64d504e8dea5#commitcomment-74042074

**Comment by ci7lus** [comment]
@humiaozuzu Will this build work with mirakc? https://github.com/ci7lus/MirakTest/actions/runs/2355934137

**Comment by humiaozuzu** [comment]
It's working now. 

Thank you for making such a great app.
