### ISSUE TITLE
Windows版v2.0.0-RC1にて、プラグインフォルダが開けない

### ISSUE THREAD

**Issue by shirow-github** [ci7lus/MirakTest#68]
「設定」から、「プラグインフォルダを開く」を選択すると、以下のメッセージが出て
プラグインフォルダが開けない。

'-------------------------------------------------
'C:\Users\hoge\AppData\Roaming\MirakTest/plugins' が見つかりません。名前を正しく入力したかどうかを確認してから、やり直してください。
'-------------------------------------------------

・・・\MirakTest/　←ここが /(スラッシュ)になっているのが原因だと思います。
確認の程よろしくお願いします。

**Comment by ci7lus** [comment]
原因っぽいところ変えてみたので https://github.com/ci7lus/MirakTest/actions/runs/2590152833 のArtifactsにあるやつで行けるか試してもらえますか？
