### ISSUE TITLE
再読み込みするとプレイヤーの FPS が下がる

### ISSUE THREAD

**Issue by rokoucha** [ci7lus/MirakTest#7]
多分 vlc が増えてる

**Comment by ci7lus** [comment]
再読み込みを単純なrelaodではなくReactのビューをすべてdestroyしてからrelaodにしないと離さないままリロードしてそう

**Comment by ci7lus** [comment]
様子見

**Comment by ci7lus** [comment]
なんか大丈夫そうな気がしてきた、問題がある場合再度Openしてください
